---
title: "Exploring Variability in Image Segmentation Models on a Pre-established Brain MRI Dataset"
author:  
  - Murat Şahin^[Mersin University, 18155057@mersin.edu.tr]
  - Berkay Şahin^[Mersin University, 18155027@mersin.edu.tr]
  - Mehmet Said Adıgüzel^[Mersin University, 19155044@mersin.edu.tr]
output:
  pdf_document:
    extra_dependencies: ["geometry"]
header-includes:
  - \usepackage{setspace}
  - \setstretch{1.5}
geometry: "a4paper, margin=0.9in, includehead, includefoot, heightrounded, marginparwidth=1in"
fontsize: 12pt
bibliography: references.bib
csl: style.csl
---

\centerline{\small \textbf{Abstract}}

Recent studies have discovered clear associations between lower-grade glioma tumors and their shape features. In this study, we aim to explore the performance of various medical image segmentation models using deep learning techniques and to test the predictive outcomes for different tumor genomic sub types.\

  We used data from a previous study [@BUDA2019218], which includes preoperative imaging of 110 patients with lower-grade gliomas from five institutions participating in The Cancer Genome Atlas. From this data, three features were extracted to quantify the two-dimensional and three-dimensional characteristics of the tumors.\
  
  We found that the most effective model for automatic tumor segmentation was U-Net, with an accuracy of 80%, followed by PSP-Net at 70%. In brain MRI glioma analysis, radiologist annotations are considered the gold standard. The study by [@BUDA2019218] involved two expert raters who achieved an 84% Dice coefficient, placing these algorithms within the acceptable range.
\vfill

__Keywords:__ brain segmentation; variability analysis; MRI; LGG; medical imaging
\newpage
\leftline{\large \textbf{1\hspace{1cm}Introduction}}
\vspace{0.5cm}
Medical imaging often suffers from the inter-observer variability, which refers to the difference in observations made by different observers on the same case. We aim to compare and test various deep learning methods for medical imaging that could potentially be used to mitigate this issue to some extent. 

Deep Learning, a relatively new advancement in machine learning, has significantly improved image segmentation and analysis performance. This progress has paved the way for automating medical image segmentation, a field that relies on expert analysis.

Some deep learning applications in this regard, has become an integral part of medical imaging. Notable examples include the classification of lung nodules, breast cancer detection in mammograms, brain tumor segmentation and the prediction of Alzheimer's disease progression. Even with a brief overview, it's evident that deep learning has revolutionized the field of medical imaging.

Given the rapid advancements in this field, testing models against diverse datasets is crucial for retrospectively optimizing them for performance.

In our case, achieving a high dice coefficient value would enable the automation of tumor identification from MRI images. This would provide a fast and cost-effective alternative or support service for experts, offering a valuable second opinion.

The following sections include a description of the data, the models used and their evaluation, a comparison of model evaluations, a discussion of our findings, and the conclusion.

IMPORTANCE OF SKIP CONNECTIONS

\newpage